// Even Fibonacci numbers
// Problem 2 
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

console.log('Euler 2 by stephan')
class Euler2 {
    static maxValue = 4000000
    previousValue = 1
    currentValue = 2
    sum = 0
    constructor() {
        while(this.currentValue <= Euler2.maxValue){
            if(this.currentValue%2 === 0) {
                this.sum = this.sum + this.currentValue
            }
           this.nextValue()
        }
        console.log('The sum of all even-valued Fibonacci <= 4million is', this.sum)
    }

    nextValue() {
        let val = this.currentValue + this.previousValue
        this.previousValue = this.currentValue
        this.currentValue = val
        return val
    }
}

new Euler2()

